s3822042/Web_Programming_Group16

README.md

Added me on the list of README to try Git commands after a while :))

Added my name just to try

---

Assignment 1/css/store/store_Apple.module.css
Assignment 1/css/store/store_Nike.module.css
Assignment 1/css/store/store_Rolex.module.css
Assignment 1/templates/store/store_Apple.html
Assignment 1/templates/store/store_Nike.html
Assignment 1/templates/store/store_Rolex.html

Adjusted nav bar, middle footer: content, position + Adjusted hover state of nav bar content

style: :art: Adjusted footer + header as ASM required

---

Assignment 1/css/store/Apple_about.module.css
Assignment 1/css/store/Nike_about.module.css
Assignment 1/css/store/Rolex_about.module.css
Assignment 1/templates/store/Apple_about.html
Assignment 1/templates/store/Nike_about.html
Assignment 1/templates/store/Rolex_about.html

Added and edited About Us Page for all stores

feat: Added stores' About Us

---

Assignment 1/css/product.module.css
Assignment 1/templates/product/nike_shoe.html

feat(product layout): :sparkles: The first product Nike shoe

---

Assignment 1/css/index.module.css
Assignment 1/index.html

Adjusted contents: photos, positions, descriptions; and positions for Index page

style: :art: Adjusted content and style for Index

---

Assignment 1/css/browse-by-cate.module.css
Assignment 1/css/browse-by-letters.module.css
Assignment 1/css/browse-menu.module.css
Assignment 1/templates/browse-by-cate.html
Assignment 1/templates/browse-by-letters.html
Assignment 1/templates/browse-menu.html

This is a "browse-menu" page with 2 submenu "browse-by-letters" and "browse-by-categories"

feat: :sparkles: Browse pages

---

js/cookies-consent.js
templates/browse-by-cate.html
templates/browse-by-letters.html
templates/browse-menu.html
templates/forgot-password.html
templates/login-form.html
templates/sign-up-form.html

Tu huy asm2

---

css/contact.module.css
css/index.module.css
templates/contact.html

Completed feature 4 which is for Contact page and made needed styling adjustments

Drew asm2 feature 4

---

css/cart.module.css
css/store/store_Nike.module.css
js/cart.js
templates/cart.html
templates/thank_you.html

- Finalize styling and adding features for my part

Add entering coupon feature for Cart page

---

js/cart.js

handle button function when coupon is wrong

fix: handle button outliners

---

templates/cart.html

fix Sign In link on nav bar of Cart page

fix: :bug: fix link on nav bar

---

templates/Privacy_Policies_CMS.php
templates/browse-by-cate.php
templates/browse-by-letters.php
templates/login-form.php
templates/privacy_policies.php
templates/term_of_services.php

- Add exceptions for Term of Service PHP file if there is no data in $_SESSION
- Little adjustment of Buttons text values 
- Fix links leading to login-form.html for available PHP files at the moment
- Add php codes to prevent execution if INSTALL.PHP exists so IF NEEDED PLS DELETE INSTALL.PHP TO TEST CMS FEATURE
- Pls leave the comments that are in the files, those are for testing
CONCLUSION: FEATURE 3 FOR ASM3 IS NOW COMPLETED.
Andrew - May 13 2021 09:58

LAST half of CMS feature of ASM 3 (feature 3)

---

php/data.txt
php/install.php
templates/About_Us_CMS.php
templates/CMS.php
templates/about.php
templates/login-form.php

- Change content of login-form.php
- Change content of install.php and data.txt (automatically after testing install.php)
- The new password (DECRYPTED): haha12345678 - USE THIS FOR TESTING

add in encrypt and decrypt feature 

---

templates/About_Us_CMS.php
templates/CMS.php
templates/Privacy_Policies_CMS.php
templates/Term_Of_Services_CMS.php

- Add Log Out option for CMS page 
- fix saving changes problems for CMS pages
Andrew Le, 18/05/21 2:06 pm

CMS Feature adjusting

---

index.php
templates/About_Us_CMS.php
templates/CMS.php
templates/Privacy_Policies_CMS.php
templates/Term_Of_Services_CMS.php
templates/about.php
templates/browse-by-cate.php
templates/browse-by-letters.php
templates/cart.php
templates/login-form.php
templates/privacy_policies.php
templates/product/Product_homepage.php
templates/sign-up-form.php
templates/term_of_services.php
templates/thank_you.php

fix SESSION HEADERS HAVE BEEN SENT error by adding conditiions on top of PHP files

fix: :bug: adjust php files content

---

index.php
templates/browse-menu.php
templates/contact.php
templates/faq.php
templates/fees.php

fix nav bar link for INDEX page + add install detection for files dont have

fix: :bug: fix nav bar link + install detection

---

templates/cart.php
templates/store/Store_homepage.php

add nav bar CART update for Store Home

fix: 🎨 add nav bar CART update

---

css/browse-by-time.module.css
templates/browse-by-created-time.php

add feature 08 for browse store homepage

feat: :zap: add feature 08

---

css/browse-by-time.module.css
css/store/store_homepage.module.css
php/browse_time_require.php
templates/browse-by-created-time.php
templates/browse-menu.php
templates/store/Store_homepage.php

- Adjust styling for Browse By Time + improve fucntion by not printing null value in product arrays + connect Browse By Time with Store Home Page 
- Fix navigation links

 adjust styling + improve function + connect feature + fix links

---

php/mall_page.php
templates/account/account.php

fix email display error for account page + fix install.php detection for index.php

fix: :bug: fix display error + fix install.php error detection

---

php/signup_require.php

store all info when sign up instead of just email and phone for feature 5

feat: :zap: add content of feature 5
